steps:

# Build the pod's docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_NAME/helloword-demo:$TAG_NAME', '.']
  #                             your GCP project name          this is git tag

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_NAME/helloword-demo:$TAG_NAME']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gs://k8stthaohelloworddemo/deployment.yaml
  - --image=gcr.io/$PROJECT_NAME/helloword-demo:$TAG_NAME
  - --location=asia-southeast1-a
  - --cluster=nn-k8s-cluster
